apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-green
  labels:
    app: todo-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
      version: green
  template:
    metadata:
      labels:
        app: todo-app
        version: green
    spec:
      containers:
      - name: todo-app
        image: rishaan03/todo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "green-2.0"
        - name: ENV_COLOR
          value: "green"
        - name: PORT
          value: "5000"
        volumeMounts:
        - name: todo-data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: todo-data
        emptyDir: {}
